platform :ios, '8.0'

target ‘BTE’ do
pod 'AFNetworking',  '~> 3.1.0'
pod 'Masonry',  '~> 1.1.0'
pod 'SDWebImage',  '~> 4.2.2'
pod 'MJRefresh',  '~> 3.1.15.1'
pod 'YYModel',  '~> 1.0.4'
pod 'MBProgressHUD',  '~> 1.1.0'
pod 'Bugly',  '~> 2.5.0'
pod 'SGQRCode',  '~> 2.1.8'
pod 'UMCAnalytics'
pod 'UMCErrorCatch'
pod 'UMCShare/UI'
pod 'UMCShare/Social/ReducedWeChat'
pod 'UMCShare/Social/ReducedQQ'
pod 'UMCShare/Social/ReducedSina'
pod 'UMCShare/Social/TencentWeibo'
pod 'JPush'
end
